### ISSUE TITLE
Bug: cannot find supported_preprocessor

### ISSUE THREAD

**Issue by George0726** [light-and-ray/sd-webui-lama-cleaner-masked-content#5]
Hi author, I tried to use your extention in sd-webui. However, it seems that I cannot import the supported_preprocessor.

`now do sd hijack: we add clip here 
Applying attention optimization: xformers... done.
Model loaded in 237.6s (load weights from disk: 22.3s, create model: 0.7s, apply weights to model: 213.8s, load textual inversion embeddings: 0.3s, calculate empty prompt: 0.2s).
*** Error running before_process: /mnt/nfs/file_server/public/stable-diffusion-webui/extensions/sd-webui-lama-cleaner-masked-content/scripts/lama_cleaner_masked_content_sctipt.py
    Traceback (most recent call last):
      File "/mnt/nfs/file_server/public/stable-diffusion-webui/modules/scripts.py", line 610, in before_process
        script.before_process(p, *script_args)
      File "/mnt/nfs/file_server/public/stable-diffusion-webui/extensions/sd-webui-lama-cleaner-masked-content/scripts/lama_cleaner_masked_content_sctipt.py", line 35, in before_process
        p.init_images[0] = lamaInpaint(p.init_images[0], p.image_mask,
      File "/mnt/nfs/file_server/public/stable-diffusion-webui/extensions/sd-webui-lama-cleaner-masked-content/lama_cleaner_masked_content/inpaint.py", line 122, in lamaInpaint
        tmpImage = lamaCNInpaint(convertIntoCNMaskedImageFromat(image256, mask256))
      File "/mnt/nfs/file_server/public/stable-diffusion-webui/extensions/sd-webui-lama-cleaner-masked-content/lama_cleaner_masked_content/inpaint.py", line 51, in lamaCNInpaint
        from scripts import supported_preprocessor
    ImportError: cannot import name 'supported_preprocessor' from 'scripts' (unknown location)`

**Comment by George0726** [comment]
version problem, need to upgrade to the latest sd-webui-controlnet version
