### ISSUE TITLE
issue with using on AMD + ZLUDA

### ISSUE THREAD

**Issue by ride5k** [light-and-ray/sd-webui-lama-cleaner-masked-content#6]
I would very much like to use this extension, however when attempting to run it the following error occurs:

```
*** Error running before_process: T:\auto1111\stable-diffusion-webui-directml\extensions\sd-webui-lama-cleaner-masked-content\scripts\lama_cleaner_masked_content_sctipt.py
    Traceback (most recent call last):
      File "T:\auto1111\stable-diffusion-webui-directml\modules\scripts.py", line 817, in before_process
        script.before_process(p, *script_args)
      File "T:\auto1111\stable-diffusion-webui-directml\extensions\sd-webui-lama-cleaner-masked-content\scripts\lama_cleaner_masked_content_sctipt.py", line 35, in before_process
        p.init_images[0] = lamaInpaint(p.init_images[0], p.image_mask,
      File "T:\auto1111\stable-diffusion-webui-directml\extensions\sd-webui-lama-cleaner-masked-content\lama_cleaner_masked_content\inpaint.py", line 122, in lamaInpaint
        tmpImage = lamaCNInpaint(convertIntoCNMaskedImageFromat(image256, mask256))
      File "T:\auto1111\stable-diffusion-webui-directml\extensions\sd-webui-lama-cleaner-masked-content\lama_cleaner_masked_content\inpaint.py", line 53, in lamaCNInpaint
        return lama(image, None).value
      File "T:\auto1111\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\scripts\preprocessor\lama_inpaint.py", line 42, in __call__
        prd_color = self.model(img_res)
      File "T:\auto1111\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\annotator\lama\__init__.py", line 54, in __call__
        result = self.model(image_feed)[0]
      File "T:\auto1111\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
      File "T:\auto1111\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
        return forward_call(*args, **kwargs)
      File "T:\auto1111\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\annotator\lama\saicinpainting\training\modules\ffc.py", line 419, in forward
        return self.model(input)
      File "T:\auto1111\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
      File "T:\auto1111\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
        return forward_call(*args, **kwargs)
      File "T:\auto1111\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\container.py", line 217, in forward
        input = module(input)
      File "T:\auto1111\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
      File "T:\auto1111\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
        return forward_call(*args, **kwargs)
      File "T:\auto1111\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\annotator\lama\saicinpainting\training\modules\ffc.py", line 337, in forward
        x_l, x_g = self.conv1((x_l, x_g))
      File "T:\auto1111\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
      File "T:\auto1111\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
        return forward_call(*args, **kwargs)
      File "T:\auto1111\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\annotator\lama\saicinpainting\training\modules\ffc.py", line 304, in forward
        x_l, x_g = self.ffc(x)
      File "T:\auto1111\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
      File "T:\auto1111\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
        return forward_call(*args, **kwargs)
      File "T:\auto1111\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\annotator\lama\saicinpainting\training\modules\ffc.py", line 275, in forward
        out_xg = self.convl2g(x_l) * l2g_gate + self.convg2g(x_g)
      File "T:\auto1111\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
      File "T:\auto1111\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
        return forward_call(*args, **kwargs)
      File "T:\auto1111\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\annotator\lama\saicinpainting\training\modules\ffc.py", line 198, in forward
        output = self.fu(x)
      File "T:\auto1111\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
      File "T:\auto1111\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
        return forward_call(*args, **kwargs)
      File "T:\auto1111\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\annotator\lama\saicinpainting\training\modules\ffc.py", line 86, in forward
        ffted = torch.fft.rfftn(x, dim=fft_dim, norm=self.fft_norm)
    RuntimeError: cuFFT error: CUFFT_INTERNAL_ERROR

---
```

i understand if this is not something that can be helped, but i wanted to ask and/or document the issue.

**Comment by light-and-ray** [comment]
I think you should better reproduce this inside controlnet preprocessor inpaint+lama, and  report here: https://github.com/Mikubill/sd-webui-controlnet

I think this is the same issue, but it should has better name https://github.com/Mikubill/sd-webui-controlnet/issues/2736

**Comment by ride5k** [comment]
yes, it is indeed the same issue... thank you!
